In [1]:
import pandas as pd
import numpy as np

In [2]:
# Read movie dataset

i_cols= ['movie id', 'movie title' ,'release date','video release date', 'IMDb URL', 'unknown', 'Action', 'Adventure',
    'Animation', 'Children\'s', 'Comedy', 'Crime', 'Documentary', 'Drama', 'Fantasy',
    'Film-Noir', 'Horror', 'Musical', 'Mystery', 'Romance', 'Sci-Fi', 'Thriller', 'War', 'Western']

items = pd.read_csv( 'ml-100k/u.item',sep='|',names=i_cols, encoding='latin-1' )

In [3]:
items.head(2)

,movie id,movie title,release date,video release date,IMDb URL,unknown,Action,Adventure,Animation,Children's,...,Fantasy,Film-Noir,Horror,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western
0,1,Toy Story (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Toy%20Story%2...,0,0,0,1,1,...,0,0,0,0,0,0,0,0,0,0
1,2,GoldenEye (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?GoldenEye%20(...,0,1,1,0,0,...,0,0,0,0,0,0,0,1,0,0

In [4]:
#Select only needed columns for item

movie_content=items[['movie id', 'movie title' ,'Action', 'Adventure',
    'Animation', 'Children\'s', 'Comedy', 'Crime', 'Documentary', 'Drama', 'Fantasy',
    'Film-Noir', 'Horror', 'Musical', 'Mystery', 'Romance', 'Sci-Fi', 'Thriller', 'War', 'Western']]

movie_content

,movie id,movie title,Action,Adventure,Animation,Children's,Comedy,Crime,Documentary,Drama,Fantasy,Film-Noir,Horror,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western
0,1,Toy Story (1995),0,0,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0
1,2,GoldenEye (1995),1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0
2,3,Four Rooms (1995),0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0
3,4,Get Shorty (1995),1,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0
4,5,Copycat (1995),0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1677,1678,Mat' i syn (1997),0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
1678,1679,B. Monkey (1998),0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0
1679,1680,Sliding Doors (1998),0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0
1680,1681,You So Crazy (1994),0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
1681,1682,Scream of Stone (Schrei aus Stein) (1991),0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0

In [5]:
# Create movie Vector

movie_vec=items[['Action', 'Adventure',
    'Animation', 'Children\'s', 'Comedy', 'Crime', 'Documentary', 'Drama', 'Fantasy',
    'Film-Noir', 'Horror', 'Musical', 'Mystery', 'Romance', 'Sci-Fi', 'Thriller', 'War', 'Western']]

movie_vec

,Action,Adventure,Animation,Children's,Comedy,Crime,Documentary,Drama,Fantasy,Film-Noir,Horror,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western
0,0,0,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0
1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0
2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0
3,1,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1677,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
1678,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0
1679,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0
1680,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
1681,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0

In [6]:
# Rename the index from RangeIndex(start=0, stop=1682, step=1) to RangeIndex(start=1, stop=1683, step=1)
movie_vec.index=range(1,1683)

In [7]:
movie_vector=movie_vec.T
movie_vector

,1,2,3,4,5,6,7,8,9,10,...,1673,1674,1675,1676,1677,1678,1679,1680,1681,1682
Action,0,1,0,1,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
Adventure,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Animation,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Children's,1,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
Comedy,1,0,0,1,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,1,0
Crime,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Documentary,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Drama,0,0,0,1,1,1,1,1,1,1,...,0,1,1,1,1,1,0,1,0,1
Fantasy,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Film-Noir,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Horror,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Musical,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Mystery,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Romance,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,1,0,0
Sci-Fi,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Thriller,0,1,1,0,1,0,0,0,0,0,...,1,0,0,0,0,0,1,0,0,0
War,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
Western,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [8]:
#Read the ratings dataset
r_cols= ['user_id', 'movie_id', 'rating', 'unix_timestamp']

ratings = pd.read_csv('ml-100k/u.data', sep='\t', names=r_cols,encoding='latin-1')
ratings

       user_id  movie_id  rating  unix_timestamp
0          196       242       3       881250949
1          186       302       3       891717742
2           22       377       1       878887116
3          244        51       2       880606923
4          166       346       1       886397596
...        ...       ...     ...             ...
99995      880       476       3       880175444
99996      716       204       5       879795543
99997      276      1090       1       874795795
99998       13       225       2       882399156
99999       12       203       3       879959583

[100000 rows x 4 columns]

In [9]:
## Create the content vector(user_vector and Item Vector)

In [10]:
# check for user = 1
u1=ratings[ratings['user_id']==1][['movie_id','rating']]

In [11]:
u1

       movie_id  rating
202          61       4
305         189       3
333          33       4
334         160       4
478          20       4
...         ...     ...
92049        28       4
92487       172       5
94019       122       3
96699       152       5
99073        94       2

[272 rows x 2 columns]

In [12]:
## Create content list for the user using movie vector
u1_list=[]
for i in u1['movie_id']:
    f=movie_vector[i].values
    u1_list.append(f)

In [13]:
u1_list

[array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0]),
 array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0]),
 array([1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0]),
 array([0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0]),
 array([1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0]),
 array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0]),
 array([1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0]),
 array([1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0]),
 array([0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0]),
 array([1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0]),
 array([1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0]),
 array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]),
 array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0]),
 array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0]),
 array([1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0]),
 array([1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0]),
 array([1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0]),
 array([0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0]),
 array([0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0]),
 array([0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0]),
 array([0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0]),
 array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0]),
 array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0]),
 array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0]),
 array([0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0]),
 array([0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1]),
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0]),
 array([0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0]),
 array([0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]),
 array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0]),
 array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0]),
 array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0]),
 array([1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0]),
 array([0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0]),
 array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0]),
 array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0]),
 array([1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]),
 array([0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0]),
 array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0]),
 array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0]),
 array([1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0]),
 array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0]),
 array([0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0]),
 array([0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0]),
 array([1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0]),
 array([1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0]),
 array([1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0]),
 array([1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]),
 array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0]),
 array([0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0]),
 array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0]),
 array([0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0]),
 array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0]),
 array([1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0]),
 array([1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0]),
 array([0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0]),
 array([0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0]),
 array([1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0]),
 array([1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0]),
 array([1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0]),
 array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0]),
 array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0]),
 array([1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0]),
 array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0]),
 array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0]),
 array([0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0]),
 array([0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0]),
 array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0]),
 array([0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0]),
 array([1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0]),
 array([1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0]),
 array([0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0]),
 array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0]),
 array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0]),
 array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0]),
 array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0]),
 array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0]),
 array([1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0]),
 array([0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0]),
 array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0]),
 array([0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0]),
 array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0]),
 array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0]),
 array([1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]),
 array([0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0]),
 array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0]),
 array([0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0]),
 array([1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0]),
 array([1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0]),
 array([1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0]),
 array([1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0]),
 array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0]),
 array([0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])]

In [14]:
# Converting content list in dataframe

uu1=pd.DataFrame(u1_list,columns=range(1,19))
uu1

     1   2   3   4   5   6   7   8   9   10  11  12  13  14  15  16  17  18
0     0   0   0   0   0   0   0   1   0   0   0   0   0   0   0   0   0   0
1     0   0   1   0   1   0   0   0   0   0   0   0   0   0   0   0   0   0
2     1   0   0   0   0   0   0   0   0   0   0   0   0   1   0   1   0   0
3     0   0   0   0   0   0   0   1   0   0   0   0   0   0   0   0   0   0
4     0   0   0   0   0   0   0   1   0   0   0   0   0   1   0   0   0   0
..   ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..
267   1   0   0   0   0   0   0   1   0   0   0   0   0   0   0   1   0   0
268   1   1   0   0   0   0   0   1   0   0   0   0   0   1   1   0   1   0
269   0   0   0   0   1   0   0   0   0   0   0   0   0   0   0   0   0   0
270   0   0   0   0   1   0   0   0   0   0   0   0   0   0   1   0   0   0
271   0   0   0   1   1   0   0   0   0   0   0   0   0   0   0   0   0   0

[272 rows x 18 columns]

In [15]:
# Create single vector for single user
vec=[]
for j in range(1,19):
    vec.append(sum(uu1[j])/272)
vec

[0.2757352941176471,
 0.15441176470588236,
 0.04411764705882353,
 0.09191176470588236,
 0.33455882352941174,
 0.09191176470588236,
 0.01838235294117647,
 0.39338235294117646,
 0.007352941176470588,
 0.003676470588235294,
 0.04779411764705882,
 0.04779411764705882,
 0.01838235294117647,
 0.16176470588235295,
 0.15808823529411764,
 0.19117647058823528,
 0.09191176470588236,
 0.022058823529411766]

In [16]:
##Creating user vector for all users

def users_vector(ratings,movie_vector):
    vector=[]
    for user in range(1,944):
        u1=ratings[ratings['user_id']==user][['movie_id','rating']]
        ## Create content list for the user using movie vector
        u1_list=[]
        for i in u1['movie_id']:
            f=movie_vector[i].values
            u1_list.append(f)
        uu1=pd.DataFrame(u1_list,columns=range(1,19))
        vec=[]
        for j in range(1,19):
            vec.append(sum(uu1[j])/len(u1)) ## Summ up all genre and divide it by no of movie ids
        vector.append(vec)
    return vector

In [17]:
vector=users_vector(ratings,movie_vector)
vector

[[0.2757352941176471,
  0.15441176470588236,
  0.04411764705882353,
  0.09191176470588236,
  0.33455882352941174,
  0.09191176470588236,
  0.01838235294117647,
  0.39338235294117646,
  0.007352941176470588,
  0.003676470588235294,
  0.04779411764705882,
  0.04779411764705882,
  0.01838235294117647,
  0.16176470588235295,
  0.15808823529411764,
  0.19117647058823528,
  0.09191176470588236,
  0.022058823529411766],
 [0.16129032258064516,
  0.04838709677419355,
  0.016129032258064516,
  0.06451612903225806,
  0.25806451612903225,
  0.14516129032258066,
  0.0,
  0.5645161290322581,
  0.016129032258064516,
  0.03225806451612903,
  0.03225806451612903,
  0.016129032258064516,
  0.06451612903225806,
  0.25806451612903225,
  0.06451612903225806,
  0.1935483870967742,
  0.04838709677419355,
  0.0],
 [0.25925925925925924,
  0.07407407407407407,
  0.0,
  0.0,
  0.2222222222222222,
  0.18518518518518517,
  0.018518518518518517,
  0.4074074074074074,
  0.0,
  0.037037037037037035,
  0.09259259259259259,
  0.037037037037037035,
  0.2037037037037037,
  0.09259259259259259,
  0.14814814814814814,
  0.3888888888888889,
  0.09259259259259259,
  0.0],
 [0.3333333333333333,
  0.16666666666666666,
  0.0,
  0.0,
  0.16666666666666666,
  0.16666666666666666,
  0.041666666666666664,
  0.25,
  0.0,
  0.0,
  0.041666666666666664,
  0.041666666666666664,
  0.20833333333333334,
  0.125,
  0.25,
  0.4583333333333333,
  0.08333333333333333,
  0.0],
 [0.32,
  0.18857142857142858,
  0.08,
  0.1657142857142857,
  0.4685714285714286,
  0.05142857142857143,
  0.0,
  0.15428571428571428,
  0.011428571428571429,
  0.005714285714285714,
  0.16,
  0.06857142857142857,
  0.017142857142857144,
  0.10857142857142857,
  0.18857142857142858,
  0.10857142857142857,
  0.08,
  0.011428571428571429],
 [0.11848341232227488,
  0.10426540284360189,
  0.04739336492890995,
  0.0947867298578199,
  0.3127962085308057,
  0.06635071090047394,
  0.004739336492890996,
  0.4928909952606635,
  0.014218009478672985,
  0.02843601895734597,
  0.018957345971563982,
  0.061611374407582936,
  0.05687203791469194,
  0.1943127962085308,
  0.061611374407582936,
  0.11374407582938388,
  0.0995260663507109,
  0.023696682464454975],
 [0.23573200992555832,
  0.14392059553349876,
  0.03225806451612903,
  0.08933002481389578,
  0.21836228287841192,
  0.0794044665012407,
  0.01240694789081886,
  0.36228287841191065,
  0.017369727047146403,
  0.02729528535980149,
  0.11662531017369727,
  0.06451612903225806,
  0.052109181141439205,
  0.13895781637717122,
  0.11910669975186104,
  0.19106699751861042,
  0.10173697270471464,
  0.04466501240694789],
 [0.6610169491525424,
  0.288135593220339,
  0.0,
  0.05084745762711865,
  0.1694915254237288,
  0.15254237288135594,
  0.0,
  0.288135593220339,
  0.0,
  0.01694915254237288,
  0.01694915254237288,
  0.0,
  0.01694915254237288,
  0.11864406779661017,
  0.288135593220339,
  0.3050847457627119,
  0.1864406779661017,
  0.05084745762711865],
 [0.18181818181818182,
  0.13636363636363635,
  0.0,
  0.0,
  0.2727272727272727,
  0.0,
  0.0,
  0.5,
  0.0,
  0.045454545454545456,
  0.045454545454545456,
  0.0,
  0.045454545454545456,
  0.36363636363636365,
  0.18181818181818182,
  0.22727272727272727,
  0.22727272727272727,
  0.0],
 [0.1358695652173913,
  0.07608695652173914,
  0.03804347826086957,
  0.043478260869565216,
  0.2554347826086957,
  0.08695652173913043,
  0.016304347826086956,
  0.44021739130434784,
  0.005434782608695652,
  0.04891304347826087,
  0.03260869565217391,
  0.07608695652173914,
  0.08152173913043478,
  0.1956521739130435,
  0.06521739130434782,
  0.18478260869565216,
  0.10869565217391304,
  0.02717391304347826],
 [0.18232044198895028,
  0.08839779005524862,
  0.0,
  0.03314917127071823,
  0.4088397790055249,
  0.07734806629834254,
  0.0,
  0.4530386740331492,
  0.011049723756906077,
  0.0055248618784530384,
  0.027624309392265192,
  0.0055248618784530384,
  0.06629834254143646,
  0.23204419889502761,
  0.1270718232044199,
  0.18232044198895028,
  0.09944751381215469,
  0.027624309392265192],
 [0.27450980392156865,
  0.13725490196078433,
  0.0196078431372549,
  0.058823529411764705,
  0.2549019607843137,
  0.0392156862745098,
  0.0,
  0.47058823529411764,
  0.0,
  0.0,
  0.0196078431372549,
  0.058823529411764705,
  0.058823529411764705,
  0.2549019607843137,
  0.13725490196078433,
  0.23529411764705882,
  0.13725490196078433,
  0.0392156862745098],
 [0.24528301886792453,
  0.11477987421383648,
  0.025157232704402517,
  0.08176100628930817,
  0.29559748427672955,
  0.07075471698113207,
  0.020440251572327043,
  0.34276729559748426,
  0.018867924528301886,
  0.0220125786163522,
  0.1179245283018868,
  0.04874213836477988,
  0.05188679245283019,
  0.1650943396226415,
  0.10220125786163523,
  0.19025157232704404,
  0.06446540880503145,
  0.020440251572327043],
 [0.1836734693877551,
  0.14285714285714285,
  0.061224489795918366,
  0.061224489795918366,
  0.35714285714285715,
  0.061224489795918366,
  0.02040816326530612,
  0.3979591836734694,
  0.01020408163265306,
  0.030612244897959183,
  0.01020408163265306,
  0.05102040816326531,
  0.061224489795918366,
  0.21428571428571427,
  0.1326530612244898,
  0.1326530612244898,
  0.10204081632653061,
  0.01020408163265306],
 [0.21153846153846154,
  0.11538461538461539,
  0.019230769230769232,
  0.0673076923076923,
  0.2692307692307692,
  0.057692307692307696,
  0.0,
  0.46153846153846156,
  0.028846153846153848,
  0.019230769230769232,
  0.019230769230769232,
  0.019230769230769232,
  0.0673076923076923,
  0.2403846153846154,
  0.11538461538461539,
  0.2403846153846154,
  0.09615384615384616,
  0.0],
 [0.21428571428571427,
  0.08571428571428572,
  0.05714285714285714,
  0.07857142857142857,
  0.2785714285714286,
  0.1357142857142857,
  0.0,
  0.4,
  0.007142857142857143,
  0.04285714285714286,
  0.06428571428571428,
  0.07142857142857142,
  0.05714285714285714,
  0.19285714285714287,
  0.11428571428571428,
  0.24285714285714285,
  0.09285714285714286,
  0.02142857142857143],
 [0.14285714285714285,
  0.14285714285714285,
  0.03571428571428571,
  0.10714285714285714,
  0.2857142857142857,
  0.07142857142857142,
  0.0,
  0.6071428571428571,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.17857142857142858,
  0.10714285714285714,
  0.14285714285714285,
  0.14285714285714285,
  0.0],
 [0.09025270758122744,
  0.06498194945848375,
  0.04332129963898917,
  0.06859205776173286,
  0.36823104693140796,
  0.04332129963898917,
  0.01444043321299639,
  0.5090252707581228,
  0.01444043321299639,
  0.01444043321299639,
  0.018050541516245487,
  0.08664259927797834,
  0.032490974729241874,
  0.24548736462093862,
  0.05415162454873646,
  0.08303249097472924,
  0.09747292418772563,
  0.01444043321299639],
 [0.25,
  0.15,
  0.0,
  0.05,
  0.6,
  0.0,
  0.0,
  0.55,
  0.0,
  0.0,
  0.1,
  0.05,
  0.0,
  0.25,
  0.05,
  0.1,
  0.05,
  0.05],
 [0.3958333333333333,
  0.2708333333333333,
  0.08333333333333333,
  0.16666666666666666,
  0.2916666666666667,
  0.041666666666666664,
  0.0,
  0.2708333333333333,
  0.041666666666666664,
  0.0,
  0.041666666666666664,
  0.08333333333333333,
  0.020833333333333332,
  0.16666666666666666,
  0.20833333333333334,
  0.2708333333333333,
  0.16666666666666666,
  0.0],
 [0.21787709497206703,
  0.0893854748603352,
  0.05027932960893855,
  0.0670391061452514,
  0.1787709497206704,
  0.08379888268156424,
  0.00558659217877095,
  0.26256983240223464,
  0.0111731843575419,
  0.0111731843575419,
  0.3407821229050279,
  0.03910614525139665,
  0.05027932960893855,
  0.08379888268156424,
  0.12849162011173185,
  0.3687150837988827,
  0.0335195530726257,
  0.0],
 [0.515625,
  0.2734375,
  0.0,
  0.0625,
  0.5625,
  0.0625,
  0.0,
  0.125,
  0.0078125,
  0.0078125,
  0.0390625,
  0.03125,
  0.0234375,
  0.1484375,
  0.1953125,
  0.1796875,
  0.1171875,
  0.03125],
 [0.2582781456953642,
  0.18543046357615894,
  0.0728476821192053,
  0.09933774834437085,
  0.33112582781456956,
  0.046357615894039736,
  0.006622516556291391,
  0.3576158940397351,
  0.013245033112582781,
  0.013245033112582781,
  0.033112582781456956,
  0.10596026490066225,
  0.033112582781456956,
  0.2251655629139073,
  0.1986754966887417,
  0.1390728476821192,
  0.08609271523178808,
  0.026490066225165563],
 [0.11764705882352941,
  0.11764705882352941,
  0.014705882352941176,
  0.07352941176470588,
  0.29411764705882354,
  0.11764705882352941,
  0.0,
  0.5441176470588235,
  0.0,
  0.0,
  0.029411764705882353,
  0.04411764705882353,
  0.029411764705882353,
  0.23529411764705882,
  0.08823529411764706,
  0.22058823529411764,
  0.07352941176470588,
  0.014705882352941176],
 [0.2564102564102564,
  0.19230769230769232,
  0.11538461538461539,
  0.14102564102564102,
  0.3333333333333333,
  0.02564102564102564,
  0.0,
  0.32051282051282054,
  0.01282051282051282,
  0.01282051282051282,
  0.02564102564102564,
  0.07692307692307693,
  0.02564102564102564,
  0.15384615384615385,
  0.21794871794871795,
  0.19230769230769232,
  0.11538461538461539,
  0.01282051282051282],
 [0.32710280373831774,
  0.1588785046728972,
  0.018691588785046728,
  0.037383177570093455,
  0.308411214953271,
  0.08411214953271028,
  0.0,
  0.38317757009345793,
  0.0,
  0.009345794392523364,
  0.028037383177570093,
  0.0,
  0.056074766355140186,
  0.18691588785046728,
  0.14953271028037382,
  0.27102803738317754,
  0.07476635514018691,
  0.009345794392523364],
 [0.4,
  0.16,
  0.04,
  0.04,
  0.04,
  0.04,
  0.0,
  0.48,
  0.0,
  0.0,
  0.08,
  0.04,
  0.04,
  0.12,
  0.16,
  0.52,
  0.16,
  0.0],
 [0.3291139240506329,
  0.20253164556962025,
  0.02531645569620253,
  0.0379746835443038,
  0.13924050632911392,
  0.0759493670886076,
  0.0,
  0.22784810126582278,
  0.012658227848101266,
  0.012658227848101266,
  0.27848101265822783,
  0.05063291139240506,
  0.0379746835443038,
  0.08860759493670886,
  0.34177215189873417,
  0.3924050632911392,
  0.06329113924050633,
  0.012658227848101266],
 [0.29411764705882354,
  0.029411764705882353,
  0.029411764705882353,
  0.058823529411764705,
  0.20588235294117646,
  0.14705882352941177,
  0.0,
  0.4411764705882353,
  0.0,
  0.058823529411764705,
  0.029411764705882353,
  0.0,
  0.058823529411764705,
  0.11764705882352941,
  0.11764705882352941,
  0.5,
  0.14705882352941177,
  0.029411764705882353],
 [0.4186046511627907,
  0.32558139534883723,
  0.023255813953488372,
  0.11627906976744186,
  0.4418604651162791,
  0.06976744186046512,
  0.0,
  0.27906976744186046,
  0.023255813953488372,
  0.0,
  0.0,
  0.06976744186046512,
  0.023255813953488372,
  0.27906976744186046,
  0.23255813953488372,
  0.20930232558139536,
  0.11627906976744186,
  0.023255813953488372],
 [0.1388888888888889,
  0.08333333333333333,
  0.0,
  0.0,
  0.1388888888888889,
  0.1111111111111111,
  0.08333333333333333,
  0.3611111111111111,
  0.0,
  0.1111111111111111,
  0.027777777777777776,
  0.05555555555555555,
  0.25,
  0.2777777777777778,
  0.08333333333333333,
  0.25,
  0.05555555555555555,
  0.0],
 [0.36585365853658536,
  0.24390243902439024,
  0.04878048780487805,
  0.04878048780487805,
  0.36585365853658536,
  0.0975609756097561,
  0.0,
  0.34146341463414637,
  0.0,
  0.0,
  0.04878048780487805,
  0.0,
  0.04878048780487805,
  0.1951219512195122,
  0.21951219512195122,
  0.2682926829268293,
  0.12195121951219512,
  0.0],
 [0.4583333333333333,
  0.041666666666666664,
  0.0,
  0.0,
  0.041666666666666664,
  0.125,
  0.0,
  0.375,
  0.0,
  0.0,
  0.20833333333333334,
  0.0,
  0.20833333333333334,
  0.16666666666666666,
  0.16666666666666666,
  0.625,
  0.125,
  0.0],
 [0.05,
  0.0,
  0.0,
  0.05,
  0.2,
  0.25,
  0.0,
  0.65,
  0.0,
  0.05,
  0.05,
  0.05,
  0.1,
  0.15,
  0.0,
  0.2,
  0.15,
  0.0],
 [0.44,
  0.16,
  0.0,
  0.12,
  0.28,
  0.08,
  0.0,
  0.28,
  0.0,
  0.0,
  0.0,
  0.0,
  0.16,
  0.12,
  0.12,
  0.44,
  0.08,
  0.0],
 [0.15,
  0.05,
  0.0,
  0.1,
  0.3,
  0.05,
  0.0,
  0.4,
  0.0,
  0.0,
  0.2,
  0.1,
  0.2,
  0.25,
  0.05,
  0.3,
  0.0,
  0.0],
 [0.8771929824561403,
  0.3508771929824561,
  0.0,
  0.0,
  0.05263157894736842,
  0.15789473684210525,
  0.0,
  0.12280701754385964,
  0.017543859649122806,
  0.017543859649122806,
  0.05263157894736842,
  0.0,
  0.017543859649122806,
  0.15789473684210525,
  0.2982456140350877,
  0.47368421052631576,
  0.08771929824561403,
  0.0],
 [0.2644628099173554,
  0.19008264462809918,
  0.08264462809917356,
  0.24793388429752067,
  0.35537190082644626,
  0.01652892561983471,
  0.0,
  0.19834710743801653,
  0.024793388429752067,
  0.008264462809917356,
  0.1487603305785124,
  0.09917355371900827,
  0.024793388429752067,
  0.1487603305785124,
  0.12396694214876033,
  0.19834710743801653,
  0.05785123966942149,
  0.008264462809917356],
 [0.18181818181818182,
  0.0,
  0.0,
  0.0,
  0.3181818181818182,
  0.09090909090909091,
  0.0,
  0.5,
  0.0,
  0.045454545454545456,
  0.09090909090909091,
  0.09090909090909091,
  0.13636363636363635,
  0.18181818181818182,
  0.09090909090909091,
  0.36363636363636365,
  0.0,
  0.0],
 [0.22857142857142856,
  0.05714285714285714,
  0.0,
  0.05714285714285714,
  0.3142857142857143,
  0.08571428571428572,
  0.0,
  0.5142857142857142,
  0.0,
  0.02857142857142857,
  0.02857142857142857,
  0.0,
  0.08571428571428572,
  0.08571428571428572,
  0.14285714285714285,
  0.3142857142857143,
  0.11428571428571428,
  0.0],
 [0.23076923076923078,
  0.09615384615384616,
  0.038461538461538464,
  0.057692307692307696,
  0.36538461538461536,
  0.07692307692307693,
  0.0,
  0.46153846153846156,
  0.019230769230769232,
  0.0,
  0.0,
  0.038461538461538464,
  0.038461538461538464,
  0.25,
  0.17307692307692307,
  0.19230769230769232,
  0.21153846153846154,
  0.038461538461538464],
 [0.23497267759562843,
  0.16939890710382513,
  0.07103825136612021,
  0.11475409836065574,
  0.3224043715846995,
  0.03278688524590164,
  0.00546448087431694,
  0.36065573770491804,
  0.0273224043715847,
  0.0,
  0.04371584699453552,
  0.07103825136612021,
  0.0273224043715847,
  0.23497267759562843,
  0.1366120218579235,
  0.19672131147540983,
  0.0546448087431694,
  0.01639344262295082],
 [0.23076923076923078,
  0.12669683257918551,
  0.09049773755656108,
  0.12217194570135746,
  0.3936651583710407,
  0.07692307692307693,
  0.004524886877828055,
  0.3665158371040724,
  0.027149321266968326,
  0.004524886877828055,
  0.03167420814479638,
  0.07239819004524888,
  0.03619909502262444,
  0.27149321266968324,
  0.09049773755656108,
  0.18099547511312217,
  0.08144796380090498,
  0.01809954751131222],
 [0.2913907284768212,
  0.2251655629139073,
  0.0728476821192053,
  0.10596026490066225,
  0.2913907284768212,
  0.06622516556291391,
  0.006622516556291391,
  0.33774834437086093,
  0.013245033112582781,
  0.006622516556291391,
  0.0728476821192053,
  0.09271523178807947,
  0.052980132450331126,
  0.16556291390728478,
  0.24503311258278146,
  0.2251655629139073,
  0.11920529801324503,
  0.013245033112582781],
 [0.20833333333333334,
  0.25,
  0.10416666666666667,
  0.16666666666666666,
  0.5,
  0.08333333333333333,
  0.0,
  0.25,
  0.0625,
  0.020833333333333332,
  0.020833333333333332,
  0.08333333333333333,
  0.0,
  0.1875,
  0.14583333333333334,
  0.14583333333333334,
  0.0625,
  0.0],
 [0.2962962962962963,
  0.1111111111111111,
  0.037037037037037035,
  0.07407407407407407,
  0.1111111111111111,
  0.18518518518518517,
  0.0,
  0.5555555555555556,
  0.0,
  0.0,
  0.07407407407407407,
  0.037037037037037035,
  0.14814814814814814,
  0.2962962962962963,
  0.1111111111111111,
  0.3333333333333333,
  0.18518518518518517,
  0.0],
 [0.04,
  0.04,
  0.0,
  0.04,
  0.2,
  0.12,
  0.04,
  0.48,
  0.0,
  0.04,
  0.08,
  0.04,
  0.2,
  0.12,
  0.04,
  0.2,
  0.04,
  0.0],
 [0.19696969696969696,
  0.16666666666666666,
  0.015151515151515152,
  0.10606060606060606,
  0.25757575757575757,
  0.10606060606060606,
  0.015151515151515152,
  0.45454545454545453,
  0.030303030303030304,
  0.06060606060606061,
  0.030303030303030304,
  0.06060606060606061,
  0.07575757575757576,
  0.15151515151515152,
  0.10606060606060606,
  0.18181818181818182,
  0.15151515151515152,
  0.015151515151515152],
 [0.17209302325581396,
  0.09302325581395349,
  0.09767441860465116,
  0.13488372093023257,
  0.40930232558139534,
  0.11627906976744186,
  0.009302325581395349,
  0.3302325581395349,
  0.023255813953488372,
  0.013953488372093023,
  0.08372093023255814,
  0.07906976744186046,
  0.037209302325581395,
  0.16279069767441862,
  0.13023255813953488,
  0.19069767441860466,
  0.03255813953488372,
  0.0],
 [0.0,
  0.0,
  0.0,
  0.0,
  0.08333333333333333,
  0.20833333333333334,
  0.041666666666666664,
  0.7083333333333334,
  0.0,
  0.041666666666666664,
  0.08333333333333333,
  0.041666666666666664,
  0.125,
  0.3333333333333333,
  0.0,
  0.16666666666666666,
  0.041666666666666664,
  0.0],
 [0.391304347826087,
  0.43478260869565216,
  0.0,
  0.043478260869565216,
  0.21739130434782608,
  0.043478260869565216,
  0.0,
  0.391304347826087,
  0.0,
  0.0,
  0.043478260869565216,
  0.13043478260869565,
  0.08695652173913043,
  0.34782608695652173,
  0.17391304347826086,
  0.13043478260869565,
  0.13043478260869565,
  0.043478260869565216],
 [0.16071428571428573,
  0.125,
  0.05357142857142857,
  0.07142857142857142,
  0.21428571428571427,
  0.05357142857142857,
  0.0,
  0.5357142857142857,
  0.0,
  0.03571428571428571,
  0.017857142857142856,
  0.05357142857142857,
  0.07142857142857142,
  0.16071428571428573,
  0.14285714285714285,
  0.16071428571428573,
  0.10714285714285714,
  0.0],
 [0.5357142857142857,
  0.32142857142857145,
  0.0,
  0.03571428571428571,
  0.17857142857142858,
  0.14285714285714285,
  0.0,
  0.2857142857142857,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.17857142857142858,
  0.32142857142857145,
  0.2857142857142857,
  0.14285714285714285,
  0.0],
 [0.4461538461538462,
  0.23076923076923078,
  0.046153846153846156,
  0.046153846153846156,
  0.16923076923076924,
  0.13846153846153847,
  0.015384615384615385,
  0.3230769230769231,
  0.03076923076923077,
  0.03076923076923077,
  0.046153846153846156,
  0.0,
  0.12307692307692308,
  0.15384615384615385,
  0.16923076923076924,
  0.46153846153846156,
  0.07692307692307693,
  0.0],
 [0.8095238095238095,
  0.42857142857142855,
  0.0,
  0.0,
  0.047619047619047616,
  0.14285714285714285,
  0.0,
  0.19047619047619047,
  0.0,
  0.047619047619047616,
  0.0,
  0.0,
  0.047619047619047616,
  0.14285714285714285,
  0.2857142857142857,
  0.47619047619047616,
  0.19047619047619047,
  0.0],
 [0.37433155080213903,
  0.2192513368983957,
  0.0962566844919786,
  0.13368983957219252,
  0.43315508021390375,
  0.0374331550802139,
  0.0,
  0.20855614973262032,
  0.0213903743315508,
  0.0053475935828877,
  0.053475935828877004,
  0.06951871657754011,
  0.016042780748663103,
  0.1925133689839572,
  0.19786096256684493,
  0.20855614973262032,
  0.06417112299465241,
  0.03208556149732621],
 [0.29245283018867924,
  0.16981132075471697,
  0.04716981132075472,
  0.11320754716981132,
  0.4339622641509434,
  0.07547169811320754,
  0.0,
  0.20754716981132076,
  0.02830188679245283,
  0.0,
  0.018867924528301886,
  0.02830188679245283,
  0.018867924528301886,
  0.12264150943396226,
  0.1792452830188679,
  0.25471698113207547,
  0.08490566037735849,
  0.0],
 [0.16233766233766234,
  0.1038961038961039,
  0.03896103896103896,
  0.03896103896103896,
  0.38311688311688313,
  0.09090909090909091,
  0.032467532467532464,
  0.43506493506493504,
  0.006493506493506494,
  0.01948051948051948,
  0.01948051948051948,
  0.01948051948051948,
  0.045454545454545456,
  0.24025974025974026,
  0.11688311688311688,
  0.19480519480519481,
  0.08441558441558442,
  0.006493506493506494],
 [0.19109947643979058,
  0.11518324607329843,
  0.04450261780104712,
  0.08115183246073299,
  0.2801047120418848,
  0.060209424083769635,
  0.010471204188481676,
  0.42408376963350786,
  0.013089005235602094,
  0.031413612565445025,
  0.06544502617801047,
  0.0549738219895288,
  0.041884816753926704,
  0.19633507853403143,
  0.10209424083769633,
  0.18586387434554974,

In [18]:
## Converting it into dataset

users_vector=pd.DataFrame(vector)
users_vector

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17
0,0.275735,0.154412,0.044118,0.091912,0.334559,0.091912,0.018382,0.393382,0.007353,0.003676,0.047794,0.047794,0.018382,0.161765,0.158088,0.191176,0.091912,0.022059
1,0.161290,0.048387,0.016129,0.064516,0.258065,0.145161,0.000000,0.564516,0.016129,0.032258,0.032258,0.016129,0.064516,0.258065,0.064516,0.193548,0.048387,0.000000
2,0.259259,0.074074,0.000000,0.000000,0.222222,0.185185,0.018519,0.407407,0.000000,0.037037,0.092593,0.037037,0.203704,0.092593,0.148148,0.388889,0.092593,0.000000
3,0.333333,0.166667,0.000000,0.000000,0.166667,0.166667,0.041667,0.250000,0.000000,0.000000,0.041667,0.041667,0.208333,0.125000,0.250000,0.458333,0.083333,0.000000
4,0.320000,0.188571,0.080000,0.165714,0.468571,0.051429,0.000000,0.154286,0.011429,0.005714,0.160000,0.068571,0.017143,0.108571,0.188571,0.108571,0.080000,0.011429
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
938,0.367347,0.204082,0.020408,0.020408,0.306122,0.061224,0.000000,0.367347,0.020408,0.000000,0.020408,0.020408,0.020408,0.204082,0.163265,0.244898,0.061224,0.000000
939,0.214953,0.112150,0.018692,0.046729,0.392523,0.065421,0.000000,0.448598,0.000000,0.028037,0.037383,0.065421,0.028037,0.224299,0.177570,0.186916,0.140187,0.000000
940,0.454545,0.318182,0.136364,0.090909,0.318182,0.045455,0.000000,0.227273,0.000000,0.000000,0.000000,0.045455,0.045455,0.045455,0.363636,0.318182,0.045455,0.000000
941,0.227848,0.139241,0.050633,0.164557,0.278481,0.000000,0.000000,0.392405,0.025316,0.012658,0.037975,0.063291,0.113924,0.215190,0.075949,0.253165,0.126582,0.037975
942,0.380952,0.208333,0.011905,0.053571,0.333333,0.107143,0.000000,0.339286,0.011905,0.000000,0.083333,0.023810,0.017857,0.196429,0.130952,0.208333,0.089286,0.053571

In [19]:
# Check user vector shape
users_vector.shape

(943, 18)

In [20]:
# Check movie vector shape
movie_vector.shape

(18, 1682)

In [21]:
# Dot matrix of user vector and movie vector
content_vector=np.dot(users_vector,movie_vector)

In [22]:
#Convert into dataframe
content_vector=pd.DataFrame(content_vector)
content_vectors=content_vector.T

In [23]:
content_vectors

,0,1,2,3,4,5,6,7,8,9,...,933,934,935,936,937,938,939,940,941,942
0,0.470588,0.338710,0.222222,0.166667,0.714286,0.454976,0.339950,0.220339,0.272727,0.336957,...,0.482759,0.282051,0.373239,0.375,0.518519,0.346939,0.457944,0.545455,0.493671,0.398810
1,0.621324,0.403226,0.722222,0.958333,0.617143,0.336493,0.570720,1.254237,0.545455,0.396739,...,0.482759,0.871795,0.478873,0.325,0.777778,0.816327,0.514019,1.090909,0.620253,0.797619
2,0.191176,0.193548,0.388889,0.458333,0.108571,0.113744,0.191067,0.305085,0.227273,0.184783,...,0.120690,0.282051,0.197183,0.100,0.296296,0.244898,0.186916,0.318182,0.253165,0.208333
3,1.003676,0.983871,0.888889,0.750000,0.942857,0.924171,0.816377,1.118644,0.954545,0.831522,...,0.971264,1.076923,1.007042,1.075,0.990741,1.040816,1.056075,1.000000,0.898734,1.053571
4,0.676471,0.903226,0.981481,0.875000,0.314286,0.672986,0.632754,0.745763,0.727273,0.711957,...,0.563218,0.820513,0.767606,0.775,0.648148,0.673469,0.700935,0.590909,0.645570,0.654762
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1677,0.393382,0.564516,0.407407,0.250000,0.154286,0.492891,0.362283,0.288136,0.500000,0.440217,...,0.390805,0.461538,0.478873,0.625,0.296296,0.367347,0.448598,0.227273,0.392405,0.339286
1678,0.352941,0.451613,0.481481,0.583333,0.217143,0.308057,0.330025,0.423729,0.590909,0.380435,...,0.327586,0.589744,0.415493,0.325,0.490741,0.448980,0.411215,0.363636,0.468354,0.404762
1679,0.555147,0.822581,0.500000,0.375000,0.262857,0.687204,0.501241,0.406780,0.863636,0.635870,...,0.597701,0.769231,0.697183,0.850,0.490741,0.571429,0.672897,0.272727,0.607595,0.535714
1680,0.334559,0.258065,0.222222,0.166667,0.468571,0.312796,0.218362,0.169492,0.272727,0.255435,...,0.362069,0.230769,0.338028,0.300,0.370370,0.306122,0.392523,0.318182,0.278481,0.333333
1681,0.393382,0.564516,0.407407,0.250000,0.154286,0.492891,0.362283,0.288136,0.500000,0.440217,...,0.390805,0.461538,0.478873,0.625,0.296296,0.367347,0.448598,0.227273,0.392405,0.339286

In [24]:
content_vectors.to_csv('content_vectors.csv',index=False)

In [25]:
def contentbased_vector(ratings,content_vectors,user_id,threshold):
    u2=ratings[ratings['user_id']==user_id]['movie_id'].values
    val=content_vectors[content_vectors[user_id]>(content_vectors[user_id].max()-threshold)]
    ##print(val)
    recom=[]
    for i in val.index:
        if(i in u2):
            pass
        else:
            recom.append(i)
    return recom

In [27]:
contentbased_vector(ratings,content_vectors,4,0.2)

[20, 183, 200, 256, 559]